// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelMigration() {
  return window['go']['main']['App']['CancelMigration']();
}

export function GetEnvironmentStatus() {
  return window['go']['main']['App']['GetEnvironmentStatus']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function SelectStagingFolder() {
  return window['go']['main']['App']['SelectStagingFolder']();
}

export function SelectThunderbirdFolder() {
  return window['go']['main']['App']['SelectThunderbirdFolder']();
}

export function StartMigration(arg1) {
  return window['go']['main']['App']['StartMigration'](arg1);
}
