// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelMigration():Promise<void>;

export function GetEnvironmentStatus():Promise<main.EnvironmentStatus>;

export function OpenFolder(arg1:string):Promise<void>;

export function SelectStagingFolder():Promise<string>;

export function SelectThunderbirdFolder():Promise<string>;

export function StartMigration(arg1:main.MigrationRequest):Promise<void>;
